yatube/about/urls.py
# файл about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'


urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]
handler404 = 'core.views.page_not_found'
handler403 = 'core.views.permission_denied'
handler500 = 'core.views.server_error'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    import debug_toolbar
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    """ Модель для сообществ"""
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        """Вернуть поля title как строки"""
        return f'{self.title}'

    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'


class Post(models.Model):
    """Модель для публикаций"""
    text = models.TextField(
        null=False,
        blank=False,
        verbose_name='Текст поста',
        help_text='Введите текст поста'
    )
    pub_date = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        related_name='posts',
        blank=True,
        null=True,
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост'
    )
    image = models.ImageField(
        verbose_name='Картинка',
        upload_to='posts/',
        blank=True,
        null=True,
        help_text='Выберите картинку для поста'
    )

    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        """Вернуть первые 15 символов"""
        return self.text[:15]


class Comment(models.Model):
    """Модель для комментариев"""
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Пост'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор'
    )
    text = models.TextField(
        null=False,
        blank=False,
        verbose_name='Текст комментария',
        help_text='Введите текст комментария'
    )
    created = models.DateTimeField(
        verbose_name='Дата публикации комментария',
        auto_now_add=True
    )

    class Meta:
        ordering = ('created',)
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        """Вернуть первые 15 символов"""
        return self.text[:15]


class Follow(models.Model):
    """Модель для подписок на авторов"""
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Подписчик',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Автор',
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'author'],
                name='unique_follow',
            )
        ]
        verbose_name = 'Подписка'
        verbose_name_plural = 'Подписки'

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post, User


def index(request):
    """View-функция для отображения главной страницы"""
    template = 'posts/index.html'
    index = True
    posts = Post.objects.select_related('group').order_by('-pub_date')
    paginator = Paginator(posts, settings.POSTS_PAGE_LIMIT)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
        'index': index,
    }
    return render(request, template, context)


def group_posts(request, slug):
    """View-функция для отображение страницы группы"""
    group = get_object_or_404(Group, slug=slug)
    template = 'posts/group_list.html'
    posts = group.posts.order_by('-pub_date')
    paginator = Paginator(posts, settings.POSTS_PAGE_LIMIT)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, template, context)


def profile(request, username):
    template = 'posts/profile.html'
    author = get_object_or_404(User, username=username)
    posts = author.posts.order_by('-pub_date')
    posts_count = posts.count()
    paginator = Paginator(posts, settings.POSTS_PAGE_LIMIT)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    following = False
    if request.user.is_authenticated:
        following = Follow.objects.filter(
            user=request.user,
            author=author,
        ).exists()
    show_button = request.user.is_authenticated and author != request.user
    context = {
        'page_obj': page_obj,
        'posts_count': posts_count,
        'author': author,
        'following': following,
        'is_user': show_button
    }
    return render(request, template, context)


def post_detail(request, post_id):
    template = 'posts/post_detail.html'
    post = get_object_or_404(Post, id=post_id)
    author = post.author
    posts_count = author.posts.count()
    post_title = post.text[:settings.POST_TITLE_LIMIT]
    comments = post.comments.order_by('-created')
    form = CommentForm(request.POST or None)
    context = {
        'post': post,
        'posts_count': posts_count,
        'post_title': post_title,
        'comments': comments,
        'form': form,
    }
    return render(request, template, context)


@login_required
def post_create(request):
    template = 'posts/create_post.html'
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
    )
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', request.user.username)
    groups = Group.objects.all()
    context = {
        'form': form,
        'groups': groups
    }
    return render(request, template, context)


@login_required
def post_edit(request, post_id):
    template = 'posts/create_post.html'
    post = get_object_or_404(Post, id=post_id)
    if request.user != post.author:
        return redirect('posts:post_detail', post.id)
    is_edit: bool = True
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if form.is_valid():
        post = form.save(commit=False)
        post.save()
        return redirect('posts:post_detail', post.id)
    groups = Group.objects.all()
    context = {
        'is_edit': is_edit,
        'form': form,
        'groups': groups,
        'post': post
    }
    return render(request, template, context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    template = 'posts/follow.html'
    follow = True
    posts = Post.objects.filter(author__following__user=request.user)
    paginator = Paginator(posts, settings.POSTS_PAGE_LIMIT)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
        'follow': follow,
    }
    return render(request, template, context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if author != request.user:
        Follow.objects.get_or_create(
            user=request.user,
            author=author,
        )
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    follow = get_object_or_404(Follow, user=request.user, author=author,)
    follow.delete()

    return redirect('posts:profile', username=username)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}

{% block title %}
{% if is_edit %}Редактирование поста
{% else %}Новый пост{% endif %}{% endblock %} 

{% block content %} <!DOCTYPE html> 

      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">  
                {% if is_edit %}
                  Редактировать пост
                {% else %}
                  Новый пост
                {% endif %}      
              </div>
              <div class="card-body">  
                <form method="post" action="{% if is_edit %}{% url 'posts:post_edit' post.id %}
                  {% else %}{% url 'posts:post_create' %}{% endif %}"
                  enctype="multipart/form-data">
                 
                  {% csrf_token %}
                 <!-- <input type="hidden" name="csrfmiddlewaretoken" value=""> -->           
                  <div class="form-group row my-3 p-3">
                    <label for="id_text">
                      Текст поста
                      <span class="required text-danger" >*</span>
                    </label>
                    <textarea name="text" cols="40" rows="10" class="form-control" 
                      required id="id_text"
                      >{% if is_edit %}{{ post.text }}{% else %}{% endif %}</textarea>
                    <small id="id_text-help" class="form-text text-muted">
                      {% if is_edit %}
                        Отредактированный текст поста
                      {% else %}
                        Текст нового поста
                      {% endif %}
                    </small>
                  </div>
                  <div class="form-group row my-3 p-3">
                    <label for="id_group">
                      Группа                  
                    </label>
                    <select name="group" class="form-control" id="id_group">
                      <option value="" >---------</option>
                      {% for group in groups %}
                        <option value={{group.id}} 
                          {%if post.group and post.group.id == group.id %} selected="selected" {% endif %}
                           >{{ group.title }}</option>
                      {% endfor %}
                    </select>
                    <small id="id_group-help" class="form-text text-muted">
                      {% if is_edit %}
                        Группа поста
                      {% else %}
                        Группа, к которой будет относиться пост
                      {% endif %}
                    </small>
                  </div>
                  <div class="form-group row my-3 p-3">
                    <label for="id_image">
                    Картинка                      
                    </label>
                    {% if is_edit %} 
                    На данный момент:{% if post.image %}<a href="{{ post.image.url }}">{{ post.image }} {% endif %} </a>
                    <p>
                    <input type="checkbox" name="image-clear" id="image-clear_id">
                    <label for="image-clear_id">Очистить</label><br>
                    Изменить:
                    {% endif %}
                    <input type="file" name="image" accept="image/*" class="form-control" id="id_image"
                     value={{ post.image }}>      
                  </div>
                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                      {% if is_edit %}
                        Сохранить
                      {% else %}
                        Добавить
                      {% endif %} 
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
      {% endblock %} 

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load cache %}


{% block title %}Избранные авторы{% endblock %} 

{% block content %} 
  <div class="container py-5">     
    <h1>Посты избранных авторов</h1>
      <article>
        {% include 'posts/includes/switcher.html' %}
          {% for post in page_obj %}
            {% include 'posts/includes/post_list.html' %}
           
            {% if post.group %}   
              Группа: 
              <a href="{% url 'posts:group_list' post.group.slug %}"
                > {{ post.group.title }}</a>
            {% endif %} 
            {% if not forloop.last %}<hr>{% endif %}
          {% endfor %}
          {% include 'posts/includes/paginator.html' %}
        
      </article>
  </div>  
{% endblock %} 

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}Записи сообщества {{ group.title }}{% endblock %} 

{% block content %}
      <div class="container py-5">
        <h1>{{ group.title }}</h1>
        <p>
          {{ group.description }}
        </p>
        <article>
          {% for post in page_obj %}
            {% include 'posts/includes/post_list.html' %}
            {% if not forloop.last %}<hr>{% endif %}
          {% endfor %} 
          {% include 'posts/includes/paginator.html' %}
        </article>
      </div>  
         
{% endblock %} 

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load cache %}


{% block title %}Это главная страница проекта Yatube{% endblock %} 


{% block content %} 
  <div class="container py-5">     
    <h1>Последние обновления на сайте</h1>
      <article>
      {% load cache %}
      {% cache 20 index_page %}
        {% include 'posts/includes/switcher.html' %}
          {% for post in page_obj %}
            {% include 'posts/includes/post_list.html' %}
           
            {% if post.group %}   
              Группа: 
              <a href="{% url 'posts:group_list' post.group.slug %}"
                > {{ post.group.title }}</a>
            {% endif %} 
            {% if not forloop.last %}<hr>{% endif %}
          {% endfor %}
          {% include 'posts/includes/paginator.html' %}
      {% endcache %}  
      </article>
  </div>  
{% endblock %} 

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}

{% load thumbnail %}
{% load user_filters %}

{% block title %}Пост {{ post_title }}{% endblock %} 

{% block content %} 

      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
            {% if post.group %}   
              <li class="list-group-item">
                Группа: 
                <a href="{% url 'posts:group_list' post.group.slug %}"
                > {{ post.group.title }} </a>                    
              </li>
            {% endif %} 
              <li class="list-group-item">
                Автор: {{ post.author.get_full_name }}
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  <span >{{ posts_count }}</span>
            </li>
            <li class="list-group-item">
              <a <a href="{% url 'posts:profile' post.author %}"
              > все посты пользователя</a>
              </a>
            </li>
          </ul>
        </aside>
        <article class="col-12 col-md-9">
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
          <p>
           {{ post.text }} 
          </p>
          {% if user == post.author %}
            <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}">
              редактировать запись
            </a>
          {% endif%}

          {% if user.is_authenticated%}
            <div class="card my-4">
              <h5 class="card-header">Добавить комментарий:</h5>
              <div class="card-body">
                <form method="post" action="{% url 'posts:add_comment' post.id %}">
                  {% csrf_token %}
                  <!--  <input type="hidden" name="csrfmiddlewaretoken" value=""> -->     
                  <div class="form-group mb-2">
                    {{ form.text|addclass:"form-control" }}
                  </div>
                  <button type="submit" class="btn btn-primary">Отправить</button>
                </form>
              </div>
            </div>
          {% endif %}

          {% for comment in comments %}
            <div class="media mb-4">
              <div class="media-body">
                <h5 class="mt-0">
                  <a href="{% url 'posts:profile' comment.author.username %}">
                    {{ comment.author.username }}
                  </a>
                </h5>
                <p>
                  {{ comment.text }}
                </p>
              </div>
            </div>
          {% endfor %}
        </article>
      </div> 

{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}Профайл пользователя {{ author.get_full_name }}{% endblock %} 

{% block content %} 

    <div class="container py-5">    
      <div class="mb-5">    
        <h1>Все посты пользователя {{ author.get_full_name }}</h1>
        <h3>Всего постов: {{ posts_count }} </h3>  
        {% if is_user %}
        {% if following %}
          <a
            class="btn btn-lg btn-light"
            href="{% url 'posts:profile_unfollow' author.username %}" role="button"
          >
           Отписаться
          </a>
        {% else %}
          <a
            class="btn btn-lg btn-primary"
            href="{% url 'posts:profile_follow' author.username %}" role="button"
          >
            Подписаться
          </a>
        {% endif %} 
        {% endif %}
        <article>
          {% for post in page_obj %}
          {% include 'posts/includes/post_list.html' %}  
            <p>
              {% if post.group %}   
                Группа:
                <a href="{% url 'posts:group_list' post.group.slug %}"
                  > {{ post.group.title }}</a>
              {% endif %} 
            </p>
            <p>  
              <a href="{% url 'posts:post_edit' post.id %}"
                > Редактировать</a>
            </p>
            {% if not forloop.last %}<hr>{% endif %}
          {% endfor %}
        {% include 'posts/includes/paginator.html' %}
        </article>       
 
    </div>

{% endblock %}